name: Validate and Format
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  format:
    runs-on: ubuntu-latest
    container: blackbird-cloud/terraform-toolkit:latest
    steps:
      - uses: actions/checkout@v3
        if: github.event.pull_request.state == 'open'
        name: Checkout

      - name: Validate and Format
        if: github.event.pull_request.state == 'open'
        run: |
          terraform init -backend=false
          terraform validate
          terraform fmt

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
