name: Validate and Format
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  format:
    runs-on: ubuntu-latest
    container: blackbird-cloud/terraform-toolkit:latest
    steps:
      - uses: actions/checkout@v3
        if: github.event.pull_request.state == 'open'
        name: Checkout
