name: Validate and Format
on: push
# on:
#   pull_request_target:
#     types: [opened, synchronize]

jobs:
  format:
    runs-on: ubuntu-latest
    container: blackbirdcloud/terraform-toolkit:latest
    steps:
      - uses: actions/checkout@v3
        # if: github.event.pull_request.state == 'open'
        name: Checkout
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Validate and Format
        env:
          TFENV_TERRAFORM_VERSION: latest-allowed
        # if: github.event.pull_request.state == 'open'
        run: |
          terraform init -backend=false
          terraform validate
          terraform fmt

      - uses: EndBug/add-and-commit@v9
        name: Commit and push
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          # ref: ${{ github.event.pull_request.head.ref }}
          default_author: github_actions
